let article_data = [{
        id: 0,
        title: "How to start Converstation",
        desc: "Full-stack Software Developer and Javascript Enthusiast, Who Loves Building Things In Javascript. 🔥 👨🏽‍💻🏅",
        img: "https://images.unsplash.com/photo-1584907797015-7554cd315667?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1176&q=80",
        detail: "Lorem ipsum dolor, sit amet consectetur adipisicing elit. Accusantium magni sint harum fugiat adipisci sunt minus possimus eum pariatur dicta veritatis, suscipit qui dolores enim. Debitis sit odio nihil temporibus necessitatibus. Error corporis voluptatum similique perferendis consectetur non, atque officia architecto. Unde distinctio maiores magnam amet minus laborum sit saepe aspernatur quia culpa incidunt placeat quo exercitationem sint hic id vero, impedit et doloribus aliquam corrupti officiis dignissimos nesciunt? Accusantium, perferendis. Ad doloremque velit accusantium iure dolore et vero dicta nostrum aspernatur dolorem aut minus ratione, autem nemo nulla labore laudantium quas at voluptates consequuntur maiores optio quia. Quo, eveniet?Lorem, ipsum dolor sit amet consectetur adipisicing elit. Ipsum distinctio magni voluptatibus iste dolore quos id. Molestiae voluptatibus officiis quos maxime ipsa obcaecati voluptate saepe debitis sint excepturi doloremque, consequuntur sapiente odit odio reprehenderit, explicabo neque amet eos repellendus. Quo, fuga tempore placeat magnam quis, commodi dolorem soluta nobis doloribus voluptatum, optio modi quibusdam totam pariatur beatae id sed. Quas quo, cumque corporis nostrum quia a, ullam nihil non laudantium, possimus saepe quis molestias quasi magnam explicabo officia eos? Dicta facilis officiis fugiat, voluptate reiciendis totam dolorum. Maiores temporibus facere quis magnam, quaerat harum laudantium tenetur pariatur ipsam tempore animi laboriosam accusamus, praesentium excepturi cumque, soluta cum nostrum at voluptate. Praesentium maiores architecto error cum velit, debitis nobis excepturi sed iure placeat laborum sint quod quisquam dolores asperiores minima nesciunt. Voluptate molestias nesciunt reprehenderit aspernatur, suscipit blanditiis cum eligendi itaque maiores officia similique, provident odio, voluptates dolorem autem obcaecati eveniet! Distinctio dignissimos in tempora ipsam unde eveniet, dolore sit non magnam natus fugiat accusamus qui facilis sequi molestiae fuga enim ea omnis quae dolorum vel at veniam modi. Nobis necessitatibus expedita molestias atque nihil sapiente quidem assumenda. Animi repudiandae pariatur obcaecati ex illum quos ipsum temporibus a eum quam! Illo."
    },
    {
        id: 1,
        title: "How not to start Converstation",
        desc: "Full-stack Software Developer and Javascript Enthusiast, Who Loves Building Things In Javascript. 🔥 👨🏽‍💻🏅",
        img: "https://media.istockphoto.com/vectors/mental-health-or-psychology-concept-with-flowering-human-head-vector-id1268669581?k=20&m=1268669581&s=612x612&w=0&h=YVLTKCZXKugEn40aqOkir4vcoFeTUAQToa1i3AFYRNU=",
        detail: "Lorem ipsum dolor, sit amet consectetur adipisicing elit. Accusantium magni sint harum fugiat adipisci sunt minus possimus eum pariatur dicta veritatis, suscipit qui dolores enim. Debitis sit odio nihil temporibus necessitatibus. Error corporis voluptatum similique perferendis consectetur non, atque officia architecto. Unde distinctio maiores magnam amet minus laborum sit saepe aspernatur quia culpa incidunt placeat quo exercitationem sint hic id vero, impedit et doloribus aliquam corrupti officiis dignissimos nesciunt? Accusantium, perferendis. Ad doloremque velit accusantium iure dolore et vero dicta nostrum aspernatur dolorem aut minus ratione, autem nemo nulla labore laudantium quas at voluptates consequuntur maiores optio quia. Quo, eveniet?Lorem, ipsum dolor sit amet consectetur adipisicing elit. Ipsum distinctio magni voluptatibus iste dolore quos id. Molestiae voluptatibus officiis quos maxime ipsa obcaecati voluptate saepe debitis sint excepturi doloremque, consequuntur sapiente odit odio reprehenderit, explicabo neque amet eos repellendus. Quo, fuga tempore placeat magnam quis, commodi dolorem soluta nobis doloribus voluptatum, optio modi quibusdam totam pariatur beatae id sed. Quas quo, cumque corporis nostrum quia a, ullam nihil non laudantium, possimus saepe quis molestias quasi magnam explicabo officia eos? Dicta facilis officiis fugiat, voluptate reiciendis totam dolorum. Maiores temporibus facere quis magnam, quaerat harum laudantium tenetur pariatur ipsam tempore animi laboriosam accusamus, praesentium excepturi cumque, soluta cum nostrum at voluptate. Praesentium maiores architecto error cum velit, debitis nobis excepturi sed iure placeat laborum sint quod quisquam dolores asperiores minima nesciunt. Voluptate molestias nesciunt reprehenderit aspernatur, suscipit blanditiis cum eligendi itaque maiores officia similique, provident odio, voluptates dolorem autem obcaecati eveniet! Distinctio dignissimos in tempora ipsam unde eveniet, dolore sit non magnam natus fugiat accusamus qui facilis sequi molestiae fuga enim ea omnis quae dolorum vel at veniam modi. Nobis necessitatibus expedita molestias atque nihil sapiente quidem assumenda. Animi repudiandae pariatur obcaecati ex illum quos ipsum temporibus a eum quam! Illo."
    },
    {
        id: 2,
        title: "Why to start Converstation",
        desc: "Full-stack Software Developer and Javascript Enthusiast, Who Loves Building Things In Javascript. 🔥 👨🏽‍💻🏅",
        img: "https://delphis.org.uk/wp-content/uploads/2018/01/Mental-Health-Continuum-Head-Surviving.png",
        detail: "Lorem ipsum dolor, sit amet consectetur adipisicing elit. Accusantium magni sint harum fugiat adipisci sunt minus possimus eum pariatur dicta veritatis, suscipit qui dolores enim. Debitis sit odio nihil temporibus necessitatibus. Error corporis voluptatum similique perferendis consectetur non, atque officia architecto. Unde distinctio maiores magnam amet minus laborum sit saepe aspernatur quia culpa incidunt placeat quo exercitationem sint hic id vero, impedit et doloribus aliquam corrupti officiis dignissimos nesciunt? Accusantium, perferendis. Ad doloremque velit accusantium iure dolore et vero dicta nostrum aspernatur dolorem aut minus ratione, autem nemo nulla labore laudantium quas at voluptates consequuntur maiores optio quia. Quo, eveniet?Lorem, ipsum dolor sit amet consectetur adipisicing elit. Ipsum distinctio magni voluptatibus iste dolore quos id. Molestiae voluptatibus officiis quos maxime ipsa obcaecati voluptate saepe debitis sint excepturi doloremque, consequuntur sapiente odit odio reprehenderit, explicabo neque amet eos repellendus. Quo, fuga tempore placeat magnam quis, commodi dolorem soluta nobis doloribus voluptatum, optio modi quibusdam totam pariatur beatae id sed. Quas quo, cumque corporis nostrum quia a, ullam nihil non laudantium, possimus saepe quis molestias quasi magnam explicabo officia eos? Dicta facilis officiis fugiat, voluptate reiciendis totam dolorum. Maiores temporibus facere quis magnam, quaerat harum laudantium tenetur pariatur ipsam tempore animi laboriosam accusamus, praesentium excepturi cumque, soluta cum nostrum at voluptate. Praesentium maiores architecto error cum velit, debitis nobis excepturi sed iure placeat laborum sint quod quisquam dolores asperiores minima nesciunt. Voluptate molestias nesciunt reprehenderit aspernatur, suscipit blanditiis cum eligendi itaque maiores officia similique, provident odio, voluptates dolorem autem obcaecati eveniet! Distinctio dignissimos in tempora ipsam unde eveniet, dolore sit non magnam natus fugiat accusamus qui facilis sequi molestiae fuga enim ea omnis quae dolorum vel at veniam modi. Nobis necessitatibus expedita molestias atque nihil sapiente quidem assumenda. Animi repudiandae pariatur obcaecati ex illum quos ipsum temporibus a eum quam! Illo."
    },
    {
        id: 3,
        title: "Getting Wierd to start Converstation",
        desc: "Full-stack Software Developer and Javascript Enthusiast, Who Loves Building Things In Javascript. 🔥 👨🏽‍💻🏅",
        img: "https://cdn.pixabay.com/photo/2021/08/21/12/41/fear-6562668__340.png",
        detail: "Lorem ipsum dolor, sit amet consectetur adipisicing elit. Accusantium magni sint harum fugiat adipisci sunt minus possimus eum pariatur dicta veritatis, suscipit qui dolores enim. Debitis sit odio nihil temporibus necessitatibus. Error corporis voluptatum similique perferendis consectetur non, atque officia architecto. Unde distinctio maiores magnam amet minus laborum sit saepe aspernatur quia culpa incidunt placeat quo exercitationem sint hic id vero, impedit et doloribus aliquam corrupti officiis dignissimos nesciunt? Accusantium, perferendis. Ad doloremque velit accusantium iure dolore et vero dicta nostrum aspernatur dolorem aut minus ratione, autem nemo nulla labore laudantium quas at voluptates consequuntur maiores optio quia. Quo, eveniet?Lorem, ipsum dolor sit amet consectetur adipisicing elit. Ipsum distinctio magni voluptatibus iste dolore quos id. Molestiae voluptatibus officiis quos maxime ipsa obcaecati voluptate saepe debitis sint excepturi doloremque, consequuntur sapiente odit odio reprehenderit, explicabo neque amet eos repellendus. Quo, fuga tempore placeat magnam quis, commodi dolorem soluta nobis doloribus voluptatum, optio modi quibusdam totam pariatur beatae id sed. Quas quo, cumque corporis nostrum quia a, ullam nihil non laudantium, possimus saepe quis molestias quasi magnam explicabo officia eos? Dicta facilis officiis fugiat, voluptate reiciendis totam dolorum. Maiores temporibus facere quis magnam, quaerat harum laudantium tenetur pariatur ipsam tempore animi laboriosam accusamus, praesentium excepturi cumque, soluta cum nostrum at voluptate. Praesentium maiores architecto error cum velit, debitis nobis excepturi sed iure placeat laborum sint quod quisquam dolores asperiores minima nesciunt. Voluptate molestias nesciunt reprehenderit aspernatur, suscipit blanditiis cum eligendi itaque maiores officia similique, provident odio, voluptates dolorem autem obcaecati eveniet! Distinctio dignissimos in tempora ipsam unde eveniet, dolore sit non magnam natus fugiat accusamus qui facilis sequi molestiae fuga enim ea omnis quae dolorum vel at veniam modi. Nobis necessitatibus expedita molestias atque nihil sapiente quidem assumenda. Animi repudiandae pariatur obcaecati ex illum quos ipsum temporibus a eum quam! Illo."
    },
    {
        id: 4,
        title: "Ok Stop to start Converstation",
        desc: "Full-stack Software Developer and Javascript Enthusiast, Who Loves Building Things In Javascript. 🔥 👨🏽‍💻🏅",
        img: "https://cdn.pixabay.com/photo/2020/06/19/17/26/mental-health-5318191__340.png",
        detail: "Lorem ipsum dolor, sit amet consectetur adipisicing elit. Accusantium magni sint harum fugiat adipisci sunt minus possimus eum pariatur dicta veritatis, suscipit qui dolores enim. Debitis sit odio nihil temporibus necessitatibus. Error corporis voluptatum similique perferendis consectetur non, atque officia architecto. Unde distinctio maiores magnam amet minus laborum sit saepe aspernatur quia culpa incidunt placeat quo exercitationem sint hic id vero, impedit et doloribus aliquam corrupti officiis dignissimos nesciunt? Accusantium, perferendis. Ad doloremque velit accusantium iure dolore et vero dicta nostrum aspernatur dolorem aut minus ratione, autem nemo nulla labore laudantium quas at voluptates consequuntur maiores optio quia. Quo, eveniet?Lorem, ipsum dolor sit amet consectetur adipisicing elit. Ipsum distinctio magni voluptatibus iste dolore quos id. Molestiae voluptatibus officiis quos maxime ipsa obcaecati voluptate saepe debitis sint excepturi doloremque, consequuntur sapiente odit odio reprehenderit, explicabo neque amet eos repellendus. Quo, fuga tempore placeat magnam quis, commodi dolorem soluta nobis doloribus voluptatum, optio modi quibusdam totam pariatur beatae id sed. Quas quo, cumque corporis nostrum quia a, ullam nihil non laudantium, possimus saepe quis molestias quasi magnam explicabo officia eos? Dicta facilis officiis fugiat, voluptate reiciendis totam dolorum. Maiores temporibus facere quis magnam, quaerat harum laudantium tenetur pariatur ipsam tempore animi laboriosam accusamus, praesentium excepturi cumque, soluta cum nostrum at voluptate. Praesentium maiores architecto error cum velit, debitis nobis excepturi sed iure placeat laborum sint quod quisquam dolores asperiores minima nesciunt. Voluptate molestias nesciunt reprehenderit aspernatur, suscipit blanditiis cum eligendi itaque maiores officia similique, provident odio, voluptates dolorem autem obcaecati eveniet! Distinctio dignissimos in tempora ipsam unde eveniet, dolore sit non magnam natus fugiat accusamus qui facilis sequi molestiae fuga enim ea omnis quae dolorum vel at veniam modi. Nobis necessitatibus expedita molestias atque nihil sapiente quidem assumenda. Animi repudiandae pariatur obcaecati ex illum quos ipsum temporibus a eum quam! Illo."
    },
]

export default article_data;